### ISSUE TITLE
Suggestion: Wired network dock

### ISSUE THREAD

**Issue by plan44** [berryelectronics/Omega2-Berrydock#1]
- mini dock style
- but with Ethernet Jack
- PPoE (passive PoE, just using free wires 4/5 7/8 for power, with down-regulator from 5..24V -> 3.3)
- maybe second Ethernet Jack (if Omega2 pinout will eventually allow that, see [here](https://community.onion.io/topic/987/omega2-documentation/2))

**Comment by berryelectronics** [comment]
closed
implemented :)
